channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=25.3
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.2
  - feature-engine==1.9.3
  - numpy==2.4.1
  - pandas==2.3.3
  - psutil==7.2.1
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.17.0
name: mlflow-env
